# Generated by Django 5.2.5 on 2025-08-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.TextField(default="Resultados Reales. <br> <span class='brand-red'>Con un Entrenamiento Real.</span>", verbose_name='Título Principal (Hero)')),
                ('hero_subtitle', models.TextField(default='Deja de adivinar en el gimnasio. Obtén un plan 100% adaptado a tu nivel, objetivos y estilo de vida.', verbose_name='Subtítulo (Hero)')),
                ('hero_button_text', models.CharField(default='Empezar mi Transformación', max_length=100, verbose_name='Texto del Botón (Hero)')),
                ('hero_background_image', models.URLField(default='http://googleusercontent.com/file_content/1', verbose_name='URL Imagen de Fondo (Hero)')),
                ('routines_title', models.CharField(default="RUTINAS <span class='brand-red'>GRATUITAS</span>", max_length=200, verbose_name='Título (Sección Rutinas)')),
                ('routines_description', models.TextField(default='Empieza a moverte con estas rutinas diseñadas para darte una idea de mi método. ¿Listo para el siguiente nivel? Contrata un plan personalizado.', verbose_name='Descripción (Sección Rutinas)')),
                ('cta_title', models.CharField(default="¿LISTO PARA UN <span class='brand-red'>CAMBIO REAL?</span>", max_length=200, verbose_name='Título (Sección CTA)')),
                ('cta_description', models.TextField(default='Mi plan de entrenamiento personalizado es más que una simple lista de ejercicios. Es tu hoja de ruta hacia el éxito.', verbose_name='Descripción (Sección CTA)')),
                ('cta_features', models.TextField(default='Planificación 100% adaptada a ti.\nAumento de masa muscular y pérdida de grasa.\nSoporte y seguimiento semanal vía WhatsApp.\nGuía de nutrición y suplementación.', help_text='Una característica por línea.', verbose_name='Características (Sección CTA)')),
                ('cta_button_text', models.CharField(default='¡Contactar por WhatsApp!', max_length=100, verbose_name='Texto del Botón (CTA)')),
                ('nutrition_title', models.CharField(default="NUTRICIÓN <span class='brand-red'>INTELIGENTE</span>", max_length=200, verbose_name='Título (Sección Nutrición)')),
                ('nutrition_description', models.TextField(default='El 70% de tus resultados se logran en la cocina. Aprende a comer para potenciar tus objetivos.', verbose_name='Descripción (Sección Nutrición)')),
                ('nutrition_image', models.URLField(default='https://placehold.co/600x400/1a1a1a/ef4444?text=Plato+Saludable', verbose_name='URL Imagen (Nutrición)')),
                ('nutrition_section_title', models.CharField(default='Comer bien no tiene por qué ser aburrido.', max_length=200, verbose_name='Subtítulo (Nutrición)')),
                ('nutrition_section_text', models.TextField(default='Te proporcionaré guías de alimentación flexibles y fáciles de seguir, basadas en tus preferencias y objetivos. Olvídate de las dietas restrictivas y aprende a construir hábitos sostenibles.', verbose_name='Texto Principal (Nutrición)')),
                ('nutrition_features', models.TextField(default='Ideas de recetas deliciosas y saludables.\nGuía de compras para el supermercado.\nEntendiendo macros y calorías sin obsesionarse.', help_text='Una característica por línea.', verbose_name='Características (Nutrición)')),
                ('blog_title', models.CharField(default="BLOG: CONOCIMIENTO <span class='brand-red'>ES PODER</span>", max_length=200, verbose_name='Título (Sección Blog)')),
                ('blog_description', models.TextField(default='Mantente actualizado con los últimos estudios y consejos sobre entrenamiento, nutrición y mentalidad.', verbose_name='Descripción (Sección Blog)')),
                ('about_image', models.URLField(default='http://googleusercontent.com/file_content/1', verbose_name='URL Imagen (Acerca de Mí)')),
                ('about_title', models.CharField(default="SOY <span class='brand-red'>BREYNER RIVEROS</span>", max_length=200, verbose_name='Título (Acerca de Mí)')),
                ('about_subtitle', models.CharField(default='Tu Coach y Aliado en esta Transformación.', max_length=200, verbose_name='Subtítulo (Acerca de Mí)')),
                ('about_text', models.TextField(default='Mi pasión por el fitness va más allá de levantar pesas...', verbose_name='Texto Principal (Acerca de Mí)')),
                ('about_button_text', models.CharField(default='Contáctame por WhatsApp', max_length=100, verbose_name='Texto del Botón (Acerca de Mí)')),
                ('whatsapp_number', models.CharField(default='573133560878', help_text="Solo números, sin el '+'", max_length=20, verbose_name='Número de WhatsApp')),
                ('instagram_url', models.URLField(default='#', verbose_name='URL de Instagram')),
                ('tiktok_url', models.URLField(default='#', verbose_name='URL de TikTok')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
    ]
