# Generated by Django 5.2.5 on 2025-08-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Imagen (Acerca de Mí)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='blog_description',
            field=models.TextField(default='Mantente actualizado...', verbose_name='Descripción (Sección Blog)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='cta_description',
            field=models.TextField(default='Mi plan de entrenamiento personalizado...', verbose_name='Descripción (Sección CTA)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='cta_features',
            field=models.TextField(default='Planificación 100% adaptada a ti.\nAumento de masa muscular...', help_text='Una característica por línea.', verbose_name='Características (Sección CTA)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Imagen de Fondo (Hero)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_subtitle',
            field=models.TextField(default='Deja de adivinar en el gimnasio...', verbose_name='Subtítulo (Hero)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nutrition_description',
            field=models.TextField(default='El 70% de tus resultados se logran en la cocina...', verbose_name='Descripción (Sección Nutrición)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nutrition_features',
            field=models.TextField(default='Ideas de recetas deliciosas...\nGuía de compras...', help_text='Una característica por línea.', verbose_name='Características (Nutrición)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nutrition_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Imagen (Nutrición)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nutrition_section_text',
            field=models.TextField(default='Te proporcionaré guías de alimentación flexibles...', verbose_name='Texto Principal (Nutrición)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='routines_description',
            field=models.TextField(default='Empieza a moverte...', verbose_name='Descripción (Sección Rutinas)'),
        ),
    ]
