# Generated by Django 5.2.5 on 2025-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_alter_siteconfiguration_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='instagram_url',
            field=models.URLField(default='https://www.instagram.com/', verbose_name='URL de Instagram'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tiktok_url',
            field=models.URLField(default='https://www.tiktok.com/', verbose_name='URL de TikTok'),
        ),
    ]
