# Generated by Django 5.0.1 on 2025-08-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_alter_siteconfiguration_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nutrition_features',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nutrition_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nutrition_section_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nutrition_section_title',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='cta_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Imagen de Fondo (CTA)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_url',
            field=models.URLField(default='#', verbose_name='URL de Facebook'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='instagram_url',
            field=models.URLField(default='#', verbose_name='URL de Instagram'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tiktok_url',
            field=models.URLField(default='#', verbose_name='URL de TikTok'),
        ),
    ]
