# Generated by Django 5.2.5 on 2025-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Publicación (Reel)', 'verbose_name_plural': 'Publicaciones (Reels)'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='...', help_text='Descripción que aparecerá junto al Reel.', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_reel_url',
            field=models.URLField(default='https://www.instagram.com/', verbose_name='URL del Reel de Instagram'),
        ),
        migrations.AddField(
            model_name='routine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='routine_images/', verbose_name='Imagen de la Rutina (miniatura)'),
        ),
        migrations.AddField(
            model_name='routine',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='routine_videos/', verbose_name='Video de la Rutina'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='description',
            field=models.TextField(default='...', verbose_name='Descripción'),
        ),
    ]
