# Generated by Django 5.0.1 on 2025-08-22 14:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_options_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Publicación de Blog', 'verbose_name_plural': 'Publicaciones de Blog'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='instagram_reel_url',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='Contenido del blog aquí...', verbose_name='Contenido del Blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog_images/', verbose_name='Imagen Principal'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Título del Blog', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='description',
            field=models.TextField(default='Descripción de la rutina aquí...', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='routine_images/', verbose_name='Imagen de la Rutina (miniatura)'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='title',
            field=models.CharField(default='Título de la Rutina', max_length=100, verbose_name='Título'),
        ),
    ]
