# Generated by Django 5.0.1 on 2025-08-22 14:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_options_remove_post_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='Para Rutinas y Nutrición.', verbose_name='Descripción Corta'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('BLOG', 'Blog'), ('RUTINA', 'Rutina'), ('NUTRICION', 'Nutrición')], default='BLOG', max_length=10, verbose_name='Tipo de Publicación'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Para Rutinas.', null=True, upload_to='post_videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Para Blogs.', null=True, verbose_name='Contenido Completo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
