# Generated by Django 5.0.1 on 2025-08-22 15:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_routine_alter_post_options_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='El contenido detallado de la publicación.', null=True, verbose_name='Contenido Completo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='Un resumen que se muestra en la página principal.', verbose_name='Descripción Corta / Resumen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Opcional: solo para Rutinas.', null=True, upload_to='post_videos/', verbose_name='Video'),
        ),
    ]
